# Generated by Django 2.2.28 on 2023-08-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bsd1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bsd2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kjj', models.BigIntegerField()),
                ('ouut', models.BigIntegerField()),
            ],
        ),
    ]
